#!/bin/bash
if [[ $UID != 0 ]]; then
    echo "Please run this script with sudo:"
    echo "sudo $0 $*"
    exit 1
fi
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
sudo avrdude -p atmega2560 -C $DIR/avrdude_gpio.conf -c pi_1 -v -U flash:w:$1:i