#!/bin/bash

/bin/echo "\e[1;33mWARNING: USE THIS TOOL WITH CARE, IT CAN BRICK YOUR CHIP\e[0m"
read -p "Press enter to continue"
sudo avrdude -p atmega2560 -C ~/avrdude_gpio.conf -c pi_1 -v -U lfuse:w:0xFF:m